# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oneof_message.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'oneof_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13oneof_message.proto\"*\n\x05Login\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"$\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"9\n\x05Order\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x1a\n\x08products\x18\x02 \x03(\x0b\x32\x08.Product\"L\n\x06Refund\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x1a\n\x08products\x18\x03 \x03(\x0b\x32\x08.Product\"`\n\nRequestMsg\x12\x17\n\x05login\x18\x01 \x01(\x0b\x32\x06.LoginH\x00\x12\x17\n\x05order\x18\x02 \x01(\x0b\x32\x06.OrderH\x00\x12\x19\n\x06refund\x18\x03 \x01(\x0b\x32\x07.RefundH\x00\x42\x05\n\x03msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oneof_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGIN']._serialized_start=23
  _globals['_LOGIN']._serialized_end=65
  _globals['_PRODUCT']._serialized_start=67
  _globals['_PRODUCT']._serialized_end=103
  _globals['_ORDER']._serialized_start=105
  _globals['_ORDER']._serialized_end=162
  _globals['_REFUND']._serialized_start=164
  _globals['_REFUND']._serialized_end=240
  _globals['_REQUESTMSG']._serialized_start=242
  _globals['_REQUESTMSG']._serialized_end=338
# @@protoc_insertion_point(module_scope)
