# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simple_message.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'simple_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14simple_message.proto\"-\n\x0e\x41notherMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05num64\x18\x02 \x01(\x03\"\xe2\x02\n\rSimpleMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05num64\x18\x02 \x01(\x03\x12\x0f\n\x07\x66loat64\x18\x03 \x01(\x01\x12\x0c\n\x04uuid\x18\x04 \x01(\x0c\x12!\n\x04type\x18\x05 \x01(\x0e\x32\x13.SimpleMessage.Type\x12\x11\n\tname_list\x18\x06 \x03(\t\x12\x12\n\nnum64_list\x18\x07 \x03(\x03\x12/\n\tmap_field\x18\x08 \x03(\x0b\x32\x1c.SimpleMessage.MapFieldEntry\x12$\n\x0b\x61nother_msg\x18\t \x01(\x0b\x32\x0f.AnotherMessage\x12%\n\x0c\x61nother_msg2\x18\n \x03(\x0b\x32\x0f.AnotherMessage\x1a/\n\rMapFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1c\n\x04Type\x12\x08\n\x04Ping\x10\x00\x12\n\n\x06Urgent\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMPLEMESSAGE_MAPFIELDENTRY']._loaded_options = None
  _globals['_SIMPLEMESSAGE_MAPFIELDENTRY']._serialized_options = b'8\001'
  _globals['_ANOTHERMESSAGE']._serialized_start=24
  _globals['_ANOTHERMESSAGE']._serialized_end=69
  _globals['_SIMPLEMESSAGE']._serialized_start=72
  _globals['_SIMPLEMESSAGE']._serialized_end=426
  _globals['_SIMPLEMESSAGE_MAPFIELDENTRY']._serialized_start=349
  _globals['_SIMPLEMESSAGE_MAPFIELDENTRY']._serialized_end=396
  _globals['_SIMPLEMESSAGE_TYPE']._serialized_start=398
  _globals['_SIMPLEMESSAGE_TYPE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
